version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - database:/code/app/database/
    env_file:
      - .env
    ports:
      - 8000:8000

volumes:
  database: