name: Tuki Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Test
        run: make test-all
