name: Tuki Testing CI
on: [push]

env:
  ENVIRONMENT: test
  TEST_DB_FILE: ./app/database/database_test.sqlite
  TEST_DIRECTORY: ./app/tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Test Game module
        run: |
          poetry run -m pytest -vv $TEST_DIRECTORY/game_tests
          rm -f $TEST_DB_FILE
