name: Tuki Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: test
      TEST_DIRECTORY: ${{ github.workspace }}/app/tests
      TEST_DB_FILE: ${{ github.workspace }}/app/database/database_test.sqlite

    steps:
      - uses: actions/checkout@v3

      - name: Install and caching poetry dependencies
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install

      - name: Test Game module
        run: |
          poetry run coverage run -m pytest $TEST_DIRECTORY/game_tests
          rm -f $TEST_DB_FILE

      - name: Test Player module
        run: |
          poetry run coverage run -m pytest $TEST_DIRECTORY/player_tests
          rm -f $TEST_DB_FILE

      - name: Test Card module
        run: |
          poetry run coverage run -m pytest $TEST_DIRECTORY/card_tests
          rm -f $TEST_DB_FILE
