name: Tuki Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: test
      TEST_DIRECTORY: ${{ github.workspace }}/app/tests
      TEST_DB_FILE: ${{ github.workspace }}/app/database/database_test.sqlite

    steps:
      - uses: actions/checkout@v3

      - name: show env
        run: env

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Test Game module
        run: |
          poetry run coverage run -m pytest $TEST_DIRECTORY/game_tests
          rm -f $TEST_DB_FILE
